services:
  web:
    container_name: pass.jarmalavicius.lt-web
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    environment:
      VIRTUAL_HOST: pass.jarmalavicius.lt
      VIRTUAL_NETWORK: nginx_proxy
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: pass.jarmalavicius.lt
      LETSENCRYPT_EMAIL: sysadmin@jarmalavicius.lt
    restart: unless-stopped

networks:
  default:
    name: nginx_proxy
    external: true
